POST  http://localhost:3000/skills.json
Content-Type: application/json

{
  "skill_name": "JavaScript"
}



### EDUCATION REQUESTS ----------------------------------------------
### education index action
GET http://localhost:3000/educations.json

### education show action
GET http://localhost:3000/educations/1.json

### education create action
POST http://localhost:3000/educations.json
Content-Type: application/json

{
  "student_id": 1,
  "degree": "test degree",
  "university_name": "test university name!",
  "details": "certificate in testing universities!"
}
# YYYY-MM-DD HH:MM:SS

### education update action
PATCH http://localhost:3000/educations/4.json
Content-Type: application/json

{
  "degree": "updated degree",
  "university_name": "updated university name!",
  "details": "certificate in updating universities!"
}

### education destroy action
DELETE http://localhost:3000/educations/3.json

### CAPSTONE REQUESTS ----------------------------------------------
### capstone index action
GET http://localhost:3000/capstones.json

### capstone show action
GET http://localhost:3000/capstones/1.json

### capstone create action
POST http://localhost:3000/capstones.json
Content-Type: application/json

{
  "student_id": 1,
  "name": "new capstone test",
  "description": "new capstone description test",
  "url": "link to new capstone",
  "screenshot": "img of new capstone!"
}

### capstone update action
PATCH http://localhost:3000/capstones/2.json
Content-Type: application/json

{
  "name": "updated capstone test",
  "description": "updated capstone description test",
  "url": "link to updated capstone",
  "screenshot": "img of updated capstone!"
}

### capstone destroy action
DELETE http://localhost:3000/capstones/2.json
