POST http://localhost:3000/experiences.json
Content-Type: application/json

{
  "student_id": 2,
  "start_date": "0001-01-05",
  "end_date": "0003-07-20",
  "job_title": "Wheelmaker",
  "company_name": "weel maker",
  "details": "i make wheel"
}
###
POST  http://localhost:3000/skills.json
Content-Type: application/json

{
  "skill_name": "JavaScript"
}



### EDUCATION REQUESTS ----------------------------------------------
### education index action
GET http://localhost:3000/students/educations.json

### education show action
GET http://localhost:3000/students/educations/1.json

### education create action
POST http://localhost:3000/students/educations.json
Content-Type: application/json

{
  "student_id": 1,
  "start_date": "2001-2-3",
  "end_date": "2004-3-25",
  "degree": "test degree",
  "university_name": "test university name!",
  "details": "certificate in testing universities!"
}
# YYYY-MM-DD HH:MM:SS

### education update action
PATCH http://localhost:3000/students/educations/8.json
Content-Type: application/json

{
  "start_date": "2001-2-3",
  "end_date": "2004-3-25",
  "degree": "updated degree",
  "university_name": "updated university name!",
  "details": "certificate in updating universities!"
}

### education destroy action
DELETE http://localhost:3000/students/educations/3.json

### CAPSTONE REQUESTS ----------------------------------------------
### capstone index action
GET http://localhost:3000/students/capstones.json

### capstone show action
GET http://localhost:3000/students/capstones/1.json

### capstone create action
POST http://localhost:3000/students/capstones.json
Content-Type: application/json

{
  "student_id": 1,
  "name": "new capstone test",
  "description": "new capstone description test",
  "url": "link to new capstone",
  "screenshot": "img of new capstone!"
}

### capstone update action
PATCH http://localhost:3000/students/capstones/2.json
Content-Type: application/json

{
  "name": "updated capstone test",
  "description": "updated capstone description test",
  "url": "link to updated capstone",
  "screenshot": "img of updated capstone!"
}

### capstone destroy action
DELETE http://localhost:3000/students/capstones/2.json
